apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - name: http
    nodePort: 31049
    protocol: TCP
    port: 8080
    targetPort: http
  selector:
    app: guestbook-ui
  type: NodePort
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-notification
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-notification
    notifications.argoproj.io/subscribe.on-sync-running.slack: argocd-notification
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd-notification
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-notification
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd-notification
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: argo-cd-deploy
